<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Diseases & Conditions - MEDIC.CO</title>
    <link href="https://fonts.googleapis.com/css2?family=Oswald:wght@300;400;500;600;700&family=Manrope:wght@300;400;500;600;700;800&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="style.css">
</head>
<body>
    <!-- Navigation -->
    <nav class="navbar">
        <div class="nav-container">
            <div class="nav-logo">
                <div class="logo-icon">
                    <div class="logo-dot"></div>
                </div>
                <span class="logo-text">MEDIC<span class="logo-accent">.CO</span></span>
            </div>
            
            <div class="nav-links">
                <a href="../web/index.php" class="nav-link">Homepage</a>
                <a href="#" class="nav-link">Services</a>
                <a href="#" class="nav-link">About Us</a>
                <a href="#" class="nav-link">Portfolio</a>
                <a href="diseases.php" class="nav-link active">Diseases & Conditions</a>
            </div>
            
            <div class="nav-actions">
                <a href="../own/login.php" class="profile-btn">
                    <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
                        <path d="M20 21v-2a4 4 0 0 0-4-4H8a4 4 0 0 0-4 4v2"></path>
                        <circle cx="12" cy="7" r="4"></circle>
                    </svg>
                </a>
            </div>
        </div>
    </nav>

    <!-- Hero Section -->
    <section class="hero">
        <div class="hero-bg"></div>
        <div class="hero-content">
            <div class="hero-badge">
                <span class="badge-dot"></span>
                <span class="badge-text">Medical Encyclopedia</span>
            </div>
            <h1 class="hero-title">
                Diseases & <br>
                <span class="hero-gradient">Conditions</span>
            </h1>
            <p class="hero-description">
                Comprehensive, expert-verified medical information at your fingertips. 
                Explore our database of over 1000+ conditions.
            </p>
        </div>
    </section>

    <!-- Disease Grid Section -->
    <section class="disease-grid-section">
        <div class="container">
            <!-- Main Card Container -->
            <div class="main-card">
                <!-- Header & Search -->
                <div class="card-header">
                    <div class="header-content">
                        <h2 class="section-title">Browse Conditions</h2>
                        <p class="section-subtitle">Find comprehensive guides by name or symptom</p>
                    </div>
                    <div class="search-container">
                        <div class="search-wrapper">
                            <svg class="search-icon" width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
                                <circle cx="11" cy="11" r="8"></circle>
                                <path d="m21 21-4.35-4.35"></path>
                            </svg>
                            <input type="text" id="searchInput" placeholder="Search diseases, symptoms (e.g. Headache)..." class="search-input">
                        </div>
                    </div>
                </div>

                <!-- Alphabet Filter -->
                <div class="alphabet-section">
                    <div class="view-all-container">
                        <button class="view-all-btn" id="viewAllBtn">
                            <span class="btn-text">View All</span>
                            <svg class="btn-icon cancel-icon" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" style="display: none;">
                                <line x1="18" y1="6" x2="6" y2="18"></line>
                                <line x1="6" y1="6" x2="18" y2="18"></line>
                            </svg>
                        </button>
                    </div>
                    <div class="alphabet-grid" id="alphabetGrid">
                        <!-- Alphabet buttons will be generated by JavaScript -->
                    </div>
                </div>
            </div>

            <!-- Results Grid -->
            <div class="results-grid" id="resultsGrid">
                <!-- Disease cards will be populated here -->
            </div>
        </div>
    </section>

    <!-- Disease Modal -->
    <div class="modal-overlay" id="diseaseModal">
        <div class="modal-card">
            <!-- Left Side -->
            <div class="modal-left">
                <div class="modal-header-mobile">
                    <span class="specialty-badge" id="modalSpecialtyMobile"></span>
                    <button class="modal-close-mobile" id="modalCloseMobile">
                        <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
                            <line x1="18" y1="6" x2="6" y2="18"></line>
                            <line x1="6" y1="6" x2="18" y2="18"></line>
                        </svg>
                    </button>
                </div>
                
                <div class="modal-specialty-desktop">
                    <span class="specialty-badge" id="modalSpecialtyDesktop"></span>
                </div>
                
                <h2 class="modal-title" id="modalTitle"></h2>
                <p class="modal-description" id="modalDescription"></p>
                
                <div class="complications-card">
                    <h4 class="complications-title">
                        <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
                            <polyline points="22,12 18,12 15,21 9,3 6,12 2,12"></polyline>
                        </svg>
                        Complications
                    </h4>
                    <p class="complications-text" id="modalComplications"></p>
                </div>
            </div>

            <!-- Right Side -->
            <div class="modal-right">
                <button class="modal-close-desktop" id="modalCloseDesktop">
                    <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
                        <line x1="18" y1="6" x2="6" y2="18"></line>
                        <line x1="6" y1="6" x2="18" y2="18"></line>
                    </svg>
                </button>

                <div class="modal-details">
                    <!-- Symptoms -->
                    <div class="detail-card symptoms-card">
                        <h3 class="detail-title">
                            <div class="detail-icon">
                                <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
                                    <path d="M9.09 9a3 3 0 0 1 5.83 1c0 2-3 3-3 3"></path>
                                    <circle cx="12" cy="17" r="1"></circle>
                                </svg>
                            </div>
                            Symptoms
                        </h3>
                        <ul class="symptoms-list" id="modalSymptoms"></ul>
                    </div>

                    <!-- Causes & Prevention -->
                    <div class="detail-grid">
                        <div class="detail-card causes-card">
                            <h3 class="detail-title">
                                <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
                                    <path d="M10.29 3.86L1.82 18a2 2 0 0 0 1.71 3h16.94a2 2 0 0 0 1.71-3L13.71 3.86a2 2 0 0 0-3.42 0z"></path>
                                    <line x1="12" y1="9" x2="12" y2="13"></line>
                                    <line x1="12" y1="17" x2="12.01" y2="17"></line>
                                </svg>
                                Causes
                            </h3>
                            <p class="detail-text" id="modalCauses"></p>
                        </div>

                        <div class="detail-card prevention-card">
                            <h3 class="detail-title">
                                <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
                                    <path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z"></path>
                                </svg>
                                Prevention
                            </h3>
                            <p class="detail-text" id="modalPrevention"></p>
                        </div>
                    </div>

                    <!-- Treatment -->
                    <div class="detail-card treatment-card">
                        <h3 class="detail-title">
                            <div class="detail-icon">
                                <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
                                    <rect x="3" y="3" width="18" height="18" rx="2" ry="2"></rect>
                                    <rect x="7" y="7" width="3" height="9"></rect>
                                    <rect x="14" y="7" width="3" height="5"></rect>
                                </svg>
                            </div>
                            Treatment
                        </h3>
                        <p class="detail-text" id="modalTreatment"></p>
                    </div>
                </div>

                <div class="modal-footer">
                    <p class="verification-text">This information is for educational purposes only and is not a substitute for professional medical advice.</p>
                </div>
            </div>
        </div>
    </div>

    <!-- Stats Section -->
    <section class="stats-section">
        <div class="container">
            <div class="stats-grid">
                <div class="stat-card">
                    <div class="stat-value">150+</div>
                    <div class="stat-label">Expert Doctors</div>
                </div>
                <div class="stat-card">
                    <div class="stat-value">1000+</div>
                    <div class="stat-label">Diseases Covered</div>
                </div>
                <div class="stat-card">
                    <div class="stat-value">50k+</div>
                    <div class="stat-label">Happy Patients</div>
                </div>
                <div class="stat-card">
                    <div class="stat-value">25+</div>
                    <div class="stat-label">Years Experience</div>
                </div>
            </div>
        </div>
    </section>

    <!-- Footer -->
    <footer class="footer">
        <p>&copy; 2024 MEDIC.CO. All rights reserved.</p>
    </footer>

    <script src="script.js"></script>
</body>
</html>